### PR TITLE
Add Rest API to check multiple feature toggles in one call

### PR DESCRIPTION
**Pull request by alexandrenavarro**
Draft PR. Comments are welcome.

### CODE REVIEW

**Review by clun — COMMENTED** [review]
I like this idea, make total sense. Only update I would make is having a `Set<String>` as input rather than list but happy to merge this feature.

**Comment by paul58914080** [comment]
> I like this idea, make total sense. Only update I would make is having a `Set<String>` as input rather than list but happy to merge this feature.

Hello @clun ,

Did you check my comment https://github.com/ff4j/ff4j-spring-boot-starter-parent/issues/137#issuecomment-694203111 ?

Do we really need this as I believe store api already gives these details ?

**Comment by alexandrenavarro** [comment]
> > I like this idea, make total sense. Only update I would make is having a `Set<String>` as input rather than list but happy to merge this feature.
> 
> Hello @clun ,
> 
> Did you check my comment [ff4j/ff4j-spring-boot-starter-parent#137 (comment)](https://github.com/ff4j/ff4j-spring-boot-starter-parent/issues/137#issuecomment-694203111) ?
> 
> Do we really need this as I believe store api already gives these details ?

@paul58914080 
I answered in https://github.com/ff4j/ff4j-spring-boot-starter-parent/issues/137 why I can't use what you propose.

**Comment by alexandrenavarro** [comment]
> I like this idea, make total sense. Only update I would make is having a `Set<String>` as input rather than list but happy to merge this feature.

Ok, you are right, I will change it. Any other comments? I didn't see any integration test for this part I'm right?

**Comment by alexandrenavarro** [comment]
I updated the PR, tell me, if you want some other modifications.

**Review by clun — APPROVED** [review]
Will merge the PR. Spring sub project is in dependency.

**Pull request merged**
